name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fruits-api/requirements.txt

    - name: Make startup script executable
      run: chmod +x fruits-api/startup.sh

    - name: Configure Azure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'fruits-api-app'
        app-settings-json: |
          {
            "WEBSITE_RUN_FROM_PACKAGE": "1",
            "PYTHONPATH": "/home/site/wwwroot",
            "PORT": "8000",
            "SCM_DO_BUILD_DURING_DEPLOYMENT": "true",
            "PYTHON_ENABLE_GUNICORN": "true"
          }

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./fruits-api
        startup-command: '/home/site/wwwroot/startup.sh' 