name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make startup script executable
      run: |
        chmod +x startup.sh

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Azure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'fruits-api-app'
        mask-inputs: true
        app-settings: |
          [
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1",
              "slotSetting": false
            },
            {
              "name": "PYTHONPATH",
              "value": "/home/site/wwwroot",
              "slotSetting": false
            },
            {
              "name": "PORT",
              "value": "8000",
              "slotSetting": false
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true",
              "slotSetting": false
            },
            {
              "name": "PYTHON_ENABLE_GUNICORN",
              "value": "true",
              "slotSetting": false
            },
            {
              "name": "WEBSITES_PORT",
              "value": "8000",
              "slotSetting": false
            }
          ]

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        startup-command: '/home/site/wwwroot/startup.sh'

    - name: Post-deployment verification
      if: success()
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 60
        echo "Checking app health..."
        curl -v https://fruits-api-app.azurewebsites.net/health || echo "Health check failed" 