name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure App Service
      run: |
        # Configure Linux container
        az webapp config set --name fruits-api-app --resource-group fruits-api-rg \
          --linux-fx-version "PYTHON|3.11" \
          --always-on true

        # Set individual app settings
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings WEBSITES_PORT=8000
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings PORT=8000
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings WEBSITE_WEBDEPLOY_USE_SCM=true
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings PYTHON_ENABLE_GUNICORN=true
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings PYTHON_VERSION=3.11
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings PYTHON_ENABLE_VENV=0
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings PYTHONPATH=/home/site/wwwroot
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings WEBSITE_RUN_FROM_PACKAGE=1
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings WEBSITE_ENABLE_SYNC_UPDATE_SITE=true
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings GUNICORN_CMD_ARGS="--workers=4 --worker-class=uvicorn.workers.UvicornWorker --timeout=600 --access-logfile=- --error-logfile=-"
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings MYSQL_USER='${{ secrets.MYSQL_USER }}'
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings MYSQL_HOST='${{ secrets.MYSQL_HOST }}'
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings MYSQL_DATABASE='${{ secrets.MYSQL_DATABASE }}'
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings STARTUP_COMMAND="gunicorn app.main:app --bind=0.0.0.0:8000 --workers=4 --worker-class uvicorn.workers.UvicornWorker --timeout 600"

        # Start the web app
        az webapp start --name fruits-api-app --resource-group fruits-api-rg

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Stream logs
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        echo "Streaming logs..."
        az webapp log tail --name fruits-api-app --resource-group fruits-api-rg || true

    - name: Post-deployment verification
      if: success()
      run: |
        echo "Checking app health..."
        curl -v https://fruits-api-app.azurewebsites.net/health || echo "Health check failed"
        
    - name: Get deployment logs
      if: always()
      run: |
        echo "Fetching deployment logs..."
        az webapp log download --name fruits-api-app --resource-group fruits-api-rg --log-file app_logs.zip
        unzip -p app_logs.zip 