name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Linux Container
      run: |
        az webapp config set --name fruits-api-app --resource-group fruits-api-rg \
          --linux-fx-version "PYTHON|3.11" \
          --always-on true

    - name: Configure App Settings
      run: |
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings \
          WEBSITES_PORT=8000 \
          SCM_DO_BUILD_DURING_DEPLOYMENT=true \
          POST_BUILD_COMMAND="pip install -r requirements.txt" \
          MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          MYSQL_HOST="${{ secrets.MYSQL_HOST }}" \
          MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}"

    - name: Create startup command file
      run: |
        echo "gunicorn --bind=0.0.0.0:8000 --workers=4 --worker-class=uvicorn.workers.UvicornWorker app.main:app" > startup.sh
        chmod +x startup.sh

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        startup-command: "startup.sh"

    - name: Stream logs
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        echo "Streaming logs..."
        az webapp log tail --name fruits-api-app --resource-group fruits-api-rg || true

    - name: Post-deployment verification
      if: success()
      run: |
        echo "Checking app health..."
        curl -v https://fruits-api-app.azurewebsites.net/health || echo "Health check failed"
        
    - name: Get deployment logs
      if: always()
      run: |
        echo "Fetching deployment logs..."
        az webapp log download --name fruits-api-app --resource-group fruits-api-rg --log-file app_logs.zip
        unzip -p app_logs.zip 