name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Stop Web App
      run: |
        az webapp stop --name fruits-api-app --resource-group fruits-api-rg

    - name: Configure Linux Container
      run: |
        az webapp config set --name fruits-api-app --resource-group fruits-api-rg \
          --linux-fx-version "PYTHON|3.11" \
          --always-on true \
          --min-tls-version 1.2 \
          --http20-enabled true

    - name: Configure App Settings
      run: |
        az webapp config appsettings set --name fruits-api-app --resource-group fruits-api-rg --settings \
          WEBSITE_RUN_FROM_PACKAGE=1 \
          PYTHONPATH=/home/site/wwwroot \
          PORT=8000 \
          SCM_DO_BUILD_DURING_DEPLOYMENT=true \
          PYTHON_ENABLE_GUNICORN=true \
          WEBSITES_PORT=8000 \
          MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          MYSQL_HOST="${{ secrets.MYSQL_HOST }}" \
          MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}" \
          WEBSITE_HTTPLOGGING_RETENTION_DAYS=7 \
          PYTHON_ENABLE_VENV=0 \
          WEBSITE_ENABLE_SYNC_UPDATE_SITE=true

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Start Web App
      run: |
        az webapp start --name fruits-api-app --resource-group fruits-api-rg

    - name: Stream logs
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        echo "Streaming logs..."
        az webapp log tail --name fruits-api-app --resource-group fruits-api-rg &
        sleep 30

    - name: Post-deployment verification
      if: success()
      run: |
        echo "Checking app health..."
        curl -v https://fruits-api-app.azurewebsites.net/health || echo "Health check failed"
        
    - name: Get deployment logs
      if: always()
      run: |
        echo "Fetching deployment logs..."
        az webapp log download --name fruits-api-app --resource-group fruits-api-rg --log-file app_logs.zip
        unzip -p app_logs.zip 