name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn

    - name: Prepare deployment package
      run: |
        # Create deployment package directory
        mkdir -p deploy_package
        # Copy necessary files
        cp -r app deploy_package/
        cp requirements.txt deploy_package/
        cp startup.sh deploy_package/
        cp web.config deploy_package/
        cp .deployment deploy_package/
        cp gunicorn.conf.py deploy_package/
        # Make startup script executable
        chmod +x deploy_package/startup.sh
        # Show package contents
        echo "Deployment package contents:"
        ls -la deploy_package/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fruits-api-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deploy_package'
        type: 'zip'

    - name: Post-deployment verification
      if: success()
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        echo "Checking app health..."
        curl -v https://fruits-api-app.azurewebsites.net/health || echo "Health check failed"
        echo "Checking app logs..."
        az webapp log tail --name fruits-api-app --resource-group fruits-api-rg || echo "Log retrieval failed" 